[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_bnpl = "66WHVPBSmijsKqa2ATUjC5LTFGbPfWrpeG3bARKexiVZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/gaopenghao/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
